name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy And Get Deployment URL
        id: get-url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_EAMON_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN --confirm --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID | grep -o 'https://[^ ]*' | head -n 1)
          echo "::set-output name=DEPLOYMENT_URL::$DEPLOYMENT_URL"

      - name: Create deployment status on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
                  "ref": "master",
                  "environment": "vercel-prod",
                  "description": "Deployment to Vercel",
                  "auto_merge": false,
                  "required_contexts": [],
                  "payload": {
                    "web_url": "'${{ steps.get-url.outputs.DEPLOYMENT_URL }}'"
                  }
                }'
