name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install Vercel CLI
        run: npm install -g vercel
    
      - name: Deploy to Vercel And Get Deployment URL
        id: get-url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name ${{secrets.VERCEL_PROJECT_EAMON_ID}}
          DEPLOYMENT_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} ls --prod | grep -o 'https://[^ ]*' | head -n 1)
          
          # 1.可设置为 环境变量，在其他步骤使用
          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> $GITHUB_ENV
          # 2.将 $DEPLOYMENT_URL 的值 赋值给当前作业的 输出变量 DEPLOYMENT_URL，在其他步骤以“steps.get-url.outputs.DEPLOYMENT_URL“形式引用（即将废弃）
          # echo "::set-output name=DEPLOYMENT_URL::$DEPLOYMENT_URL"
          # 3.也可写入txt，在其他步骤使用（查看所有 环境变量，找到 环境变量DEPLOYMENT_URL的键值对，取其值，保存为txt文本 ）
          cat $GITHUB_ENV | grep DEPLOYMENT_URL | cut -d'=' -f2 > DEPLOYMENT_URL.txt
          
          a=$(cat DEPLOYMENT_URL.txt) # 赋值表达式“=“两边 不能有空格
          echo $a
          # 打印变量（含 环境变量）的 3种 方式：echo "我是$a"、echo "我是${a}"、echo $a
    
      - name: Get Vercel Project Info
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
         curl -s -H "Authorization: Bearer $VERCEL_TOKEN" https://api.vercel.com/v6/projects/${{secrets.VERCEL_PROJECT_EAMON_ID}} > vercel_project.json
         cat vercel_project.json
    
      - name: Extract Custom Domain
        run: |
          # 提取 domain
          DOMAIN=$(cat vercel_project.json | jq -r '.alias[0].domain // empty')
          echo "Custom Domain: $DOMAIN"
          echo "CUSTOM_DOMAIN=${DOMAIN}" >> $GITHUB_ENV
          
          # 若vercel平台待部署项目 未关联域名，则使用 DEPLOYMENT_URL作为environment_url【须以https开头】
          if [ -z "$DOMAIN" ]; then
            CUSTOM_DOMAIN=$DEPLOYMENT_URL
          fi
        
      - name: Create deployment status on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
                  "ref": "master",
                  "environment": "vercel-prod",
                  "description": "Deployment to Vercel",
                  "auto_merge": false,
                  "required_contexts": [],
                  "payload": {},
                  "transient_environment": false,
                  "production_environment": true
                }' | jq -r '.id' > deployment_id.txt
    
                  # txt形式，不同步骤之间传递值
                  DEPLOYMENT_ID=$(cat deployment_id.txt)
                  # 或 环境变量 形式，不同步骤之间传递值
                  echo "DEPLOYMENT_ID=${DEPLOYMENT_ID}" >> $GITHUB_ENV
          
      - name: Update deployment status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(cat DEPLOYMENT_URL.txt)
          DEPLOYMENT_ID=$(cat deployment_id.txt)
          # 或 环境变量 DEPLOYMENT_ID=${{env.DEPLOYMENT_ID}}
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${DEPLOYMENT_ID}/statuses \
            -d '{
                  "state": "success",
                  "description": "Deployment to Vercel successful",
                  "auto_inactive": true,
                  "log_url": "'${DEPLOYMENT_URL}'",
                  "environment_url": "'https://$CUSTOM_DOMAIN'"
                }'
